### ISSUE TITLE
Fix android lint warnings and re-enable lint build step

### ISSUE THREAD

**Issue by matobet** [oVirt/moVirt#130]
The lint step was temporarily disabled on master, until all warnings can be properly fixed, in order to obtain better build error reporting from Travis CI. It was not very helpful when each commit/pull request failed CI because of this (despite compiling and passing tests).

This should of course be fixed properly by fixing the warnings and re-enabling the android lint step in gradle.

**Comment by jelkosz** [comment]
@matobet I think it is fixed now, no?

**Comment by matobet** [comment]
@jelkosz unfortunately no, please see https://github.com/matobet/moVirt/blob/master/moVirt/build.gradle#L70 :)

**Comment by jelkosz** [comment]
I don't think this is going to make 1.7, it is too much work. Removing the milestone for now
