### ISSUE TITLE
add ability to manage more ovirt installations from one movirt

### ISSUE THREAD

**Issue by jelkosz** [oVirt/moVirt#174]

**Comment by necarnot** [comment]
Thank you Tomas for opening this RFE.

**Comment by matonb** [comment]
Would be a very handy feature +1 from me

**Comment by dougti** [comment]
+1

**Comment by jelkosz** [comment]
development started, will arrive in next release

**Comment by suomiy** [comment]
testing new layout designs in #259 for this feature

**Comment by suomiy** [comment]
we should also display each engine's version

**Comment by petrilakm** [comment]
+1

**Comment by suomiy** [comment]
This feature is already implemented in our new RC.
You can try it here https://github.com/oVirt/moVirt/releases/download/v2.0-rc1/moVirt-release.apk
