### ISSUE TITLE
add the ability to create the scan code from the app and send it to your mail/printer 

### ISSUE THREAD

**Issue by shiramax** [oVirt/moVirt#204]
add the ability to create the scan code from the app and send it to your mail/printer  ( just right click on the host -> create a code, and also nice explanation about this about what do next )

**Comment by jelkosz** [comment]
@shiramax yes, this is a good idea. Other option we were considering was to create a UI plugin into webadmin doing the same. But having it in movirt does make sens, but requires to have an ability to do mass operations with more than one host.
