### ISSUE TITLE
The "Sort by" shouldn't be under the "search"

### ISSUE THREAD

**Issue by shiramax** [oVirt/moVirt#209]
it's not so Intuitively to look for the sort under the search button, 
i think it should have another button.

**Comment by jelkosz** [comment]
@shiramax yeah, but we don't really want to flood the tiny screen by many buttons. Maybe the button icon itself does not signify properly what it is. Do you have some specific icon in mind? I have one icon in mind but don't want to bias you :)

**Comment by shiramax** [comment]
@jelkosz  maybe something like this? 
![image](https://cloud.githubusercontent.com/assets/5609929/19889583/4c6f8818-a03e-11e6-9722-91ef0a5f971c.png)

**Comment by jelkosz** [comment]
@shiramax I was rather thinking about a filter icon: 

![24540](https://cloud.githubusercontent.com/assets/701107/20005911/3e852a56-a295-11e6-857a-b5da2c216810.png)

But not sure now.

@shiramax @matobet @suomiy what you think?

**Comment by suomiy** [comment]
I think sort and search are related. I am for simpler design; that is only one icon.

**Comment by jelkosz** [comment]
@jniederm you are good in UX, what you think? :)

**Comment by jniederm** [comment]
I found the funnel icon better matching our usecase.
