### ISSUE TITLE
inactive storage domain is presented as active 

### ISSUE THREAD

**Issue by shiramax** [oVirt/moVirt#224]
in movirt app, a storage domain that is not active is presented as active

**Comment by shiramax** [comment]
also storages that are in Maintenance mode are presented as active

**Comment by suomiy** [comment]
can be resolved after this bug is fixed: https://bugzilla.redhat.com/show_bug.cgi?id=1413628

**Comment by suomiy** [comment]
also UI refactoring 
- domains under datacenters and/or all domains list (dc's domains + unattached)
