### ISSUE TITLE
Device doesn't blinks when creating a trigger with 'Blink'

### ISSUE THREAD

**Issue by shiramax** [oVirt/moVirt#245]
the Device shows message and the vibrates but it doesn't blinks.

**Comment by suomiy** [comment]
It is not possible to test this on my device (no led), but I can make a fixed build for you to test it if it works. 

Btw, should vibrate option also blink?

**Comment by shiramax** [comment]
@suomiy , i  don't think that the vibrate should blink too.. 
also, is there a way to choose the color of the blink ?

**Comment by suomiy** [comment]
no it is not, but I don't think this functionality is really needed

**Comment by shiramax** [comment]
@suomiy , many apps used this, 
it allows them to see from which app the notification was received.

**Comment by suomiy** [comment]
ok, we could do it in the future
