### ISSUE TITLE
design of over commit

### ISSUE THREAD

**Issue by suomiy** [oVirt/moVirt#249]
Here is the alternative design of over commit. There is also the old one for comparison.

IMO I think it is not clear what allocated relates to now. It seems like every line is separate entity.

@jelkosz @shiramax
What do you think?

![physical-alternative](https://cloud.githubusercontent.com/assets/3648838/22508070/a4b6d03e-e888-11e6-86d9-d9b21e77e51c.png) 
![physical](https://cloud.githubusercontent.com/assets/3648838/22508076/a9b31cdc-e888-11e6-8ef0-b0a39b523bea.png)

**Comment by matobet** [comment]
CC-ing @serenamarie125

**Comment by shiramax** [comment]
@suomiy , i agree that it's not clear what allocated relates to now,
maybe you can add in the third line - "Allocated over commit "? 

BTW, In the memory section in appears that the first line is smaller..

**Comment by suomiy** [comment]
@shiramax 
 "Allocated over commit " line would be too long or it would have to be smaller. Then it would be not consistent with Over commit and I think these two should be somehow coupled or look similar.

I would keep it in the current state.

The size of memory section changes according to the length of numbers
