### ISSUE TITLE
UI error triangle redesign

### ISSUE THREAD

**Issue by suomiy** [oVirt/moVirt#262]
What would be the best way to show connection errors across multiple engines?  Current state is just a triangle when first error occurs.

some options: 

1.   error triangle with the number of failed engines like 
1/4 (Triangle)

2.  some special Triangle if there are some engines active

3.  health bar (maybe in a circle) ?

Also should we change this element depending on engine selected?

**Comment by shiramax** [comment]
Hey, 
I didn't much understand number 3, can you show an example? 

I think that for the active engine (the engine the user is in at the moment ) we should stay with the error triangle.
and for the each and every engine we should add a smaller triangle, and put it where the list of engine are presented.

**Comment by suomiy** [comment]
Hi Shira,

3 is just a wild guess. Something like dashboard outer circle around an exclamation mark but ,it would be 1/3 green 2/3 red depending on a number of  dead engines.

There will be also a list where you can see small triangle next to an engine, but I think it would be quite useful to also have a global indicator that something went wrong on some other engine than the selected one.

**Comment by suomiy** [comment]
The first option was chosen for now. Reopen this if necessary
