### ISSUE TITLE
Error parsing REST response - id should not be empty 

### ISSUE THREAD

**Issue by shiramax** [oVirt/moVirt#266]
happens after sync : 
![screenshot from 2017-05-29 15-57-56](https://cloud.githubusercontent.com/assets/5609929/26550773/f48446e0-4487-11e7-923d-1bce77b6dee1.png)

i'm not sure what's the problem,  can reproduce on only one environment,

**Comment by suomiy** [comment]
Should be fixed now. Please can you test it again (plust few other other basic features) in the same environment? The cluster doesn't seem to have a datacenter.

**Comment by shiramax** [comment]
it looks OK now, i can't do many actions in this setup because it's not really mine, what the basic feature you think it's important to test?

**Comment by suomiy** [comment]
Actually I don't know if there are any actions available for inactive cluster.

I guess browsing through moVirt and refreshing entities + also refreshing one detail per type (vm,host, snapshot) should be enough.

**Comment by shiramax** [comment]
cool, so this tests passed successfully.
