### ISSUE TITLE
Sorting of cpu usage is not working as expected. 

### ISSUE THREAD

**Issue by shiramax** [oVirt/moVirt#273]
![image](https://cloud.githubusercontent.com/assets/5609929/26784211/194a52c6-4a05-11e7-8df7-bab07fce6c73.png)
in the attachment you can see that the cpu usage of the vm's start with 100, 83...10 and then 18.

**Comment by suomiy** [comment]
I also put more reasonable defaults. So the cpu usage defaults to High to Low when you first select it. Name defaults to A to Z, etc.
