### ISSUE TITLE
in 4.2 (nightly) , the hosts memory and cpu are not correct 

### ISSUE THREAD

**Issue by shiramax** [oVirt/moVirt#285]
in 4.2 (nightly) , the host memory and cpu are not correct : 
![image](https://user-images.githubusercontent.com/5609929/27540233-25dca6f4-5a88-11e7-984a-86809a81b5ec.png)
![image](https://user-images.githubusercontent.com/5609929/27540253-3247c20c-5a88-11e7-8728-dad8f16cfe71.png)

**Comment by suomiy** [comment]
yes 4.2 is not working yet, as mentioned in #272
