### ISSUE TITLE
In Host Events, It should be only the host related Events (4.2)

### ISSUE THREAD

**Issue by shiramax** [oVirt/moVirt#286]
The Hosts Events presents the all Events and not only the host.
This bug also accure in the web  admin.

**Comment by jelkosz** [comment]
@shiramax this happens on ovirt 4.2, right? If yes than it is this bug: https://bugzilla.redhat.com/show_bug.cgi?id=1454821

**Comment by shiramax** [comment]
it does happen in 4.2, 
are you sure it's this bug? it doesn't seem related to that issue.

**Comment by jelkosz** [comment]
yep, it is. The thing is that we use search query for finding the related entities and there is a bug in the backend implementation of the search query which returns much more entities than we need asked for.

You can observe an another incarnation of this bug by going in webadmin to the VM subtab of the pool main tab and you will see all the VMs, not only the ones belonging to the pool.
