### ISSUE TITLE
Max events polled doesn't work as expected

### ISSUE THREAD

**Issue by shiramax** [oVirt/moVirt#288]
The max polled is not working correctly , when setting this number to 5, Nothing changes in the Events tab, and the amount of the Events is bigger than 5.

**Comment by suomiy** [comment]
There shouldn't be a change if you do not poll events. This should be controlled by max events stored.

max polled should just poll 5 newest in the next poll

Let me know if you disagree with anything, otherwise please close this issue.

**Comment by suomiy** [comment]
resolved
