### ISSUE TITLE
4.2 engine support on android 4.4.4

### ISSUE THREAD

**Issue by liranr23** [oVirt/moVirt#293]
The app doesn't show any error or problem, but there is no data from the engine at all in the moVirt.

**Comment by suomiy** [comment]
maybe related to other 4.2 issues, but we had at least some data in them

**Comment by jelkosz** [comment]
@liranr23 is it happening only on 4.2 engine?

**Comment by jelkosz** [comment]
btw one more thing - do you see anything in the engine log related to the communication? Some login attempt or anything?

**Comment by liranr23** [comment]
@jelkosz I tried 4.1 on it, it's working. so i think it's only on 4.2 engine.
I looked into the engine log, there is no occurrence whatsoever about the communication.

**Comment by suomiy** [comment]
it could be similar to this problem #296, but that one is happening also on 4.1. There was also a bug about reporting errors. There will be new minor version of moVirt in 1-2 days. You will see the error now.
