### ISSUE TITLE
Wrong error message

### ISSUE THREAD

**Issue by liranr23** [oVirt/moVirt#294]
# Steps to reproduce:
1. Connect to engine and see that the app got the engine data.
1. Enter to connections.
2. Set a connection with a bad URI.
3. Click on the V sign to set the connection(an error will occur).
4. Go back to the VMs menu.
5. Try to preform any action related to VM/sync/etc.

## Expected result:
Error message: 
"Could not connect, make sure ip address and port are correct"/a simple error related to the wrong connection/cleanup data after setting the wrong connection(which wouldn't let this result happen).

## Actual result:
Error message:
"REST request failed!

Connection details:
API URL: *the wrong url*
Username: admin@internal
Token:..

Error details:
...
"

**Comment by suomiy** [comment]
> 4. Click on the V sign to set the connection(an error will occur).

We expect the user to correct the ip when they get the first error

> 5. Go back to the VMs menu.

After that is not clear if the engine is down or just unreachable. Meaning the ip could be correct.

Please feel free to reopen this issue if you have any solution or other questions.
