### ISSUE TITLE
javax.net.ssl.SSLException on Android 4.4.2

### ISSUE THREAD

**Issue by atiratree** [oVirt/moVirt#296]
##### Details
- Exception Message: Connection closed by Peer
- occured on engine 4.1

##### Issue: 
TLSv1 is dissabled on the engine 

investigate and possibly fix with:
- https://stackoverflow.com/questions/37006416/sslexception-connection-closed-by-peer-on-android-4-x-versions/37021685#37021685
- https://stackoverflow.com/questions/26649389/how-to-disable-sslv3-in-android-for-httpsurlconnection

**Comment by georgeRCluj** [comment]
Very good links!
