### ISSUE TITLE
Console option not always available

### ISSUE THREAD

**Issue by jflorian** [oVirt/moVirt#303]
I don't believe I ever saw this until I upgraded from 4.1 to 4.2.3 very recently.  I have gotten the option and successful consoles thru moVirt since that upgrade, but I can find quite a number of VMs that provide no such option.  I have no problem getting a console thru the standard web interface on a regular desktop computer for the same VMs.  Any ideas of what I should be looking for?

**Comment by suomiy** [comment]
Thanks for reporting this. Could you please check the REST API of the VMs which work in webadmin but not in moVirt?

##### listing graphical consoles
```
curl -k -X GET \
  https://$ENGINE_ADDRESS/ovirt-engine/api/vms/$VM_ID/graphicsconsoles \
  -H "accept: application/xml" \
  -H "authorization: Basic $BASE_64_AUTH" 
```

##### fetching  .vv file
```
curl -k -X GET \
  https://$ENGINE_ADDRESS/ovirt-engine/api/vms/$VM_ID/graphicsconsoles/$CONSOLE_ID \
  -H "accept: application/x-virt-viewer" \
  -H "authorization: Basic $BASE_64_AUTH"
```


BASE_64_AUTH is "user@profile:password" encoded in base64

**Comment by jflorian** [comment]
Is $VM_ID simply the VM name?  If not, how can I find it?  Assuming, it is, the first curl command (listing graphical consoles) returned nothing.  Also noteworthy is that maybe perhaps these consoles aren't working from the webadmin page.  In attempting to do a desktop console for a VM where moVirt didn't offer the option, I was able to download the vv file and Remote Viewer opened a new window but rather than the actual console, the window shows a single message of "Connected to graphic server".  Although I seem to have the same desktop console problem for all VMs right now, even if moVirt does work.  Desktop was recently updated to Fedora 28 and I've been fighting other issues, but maybe this all stems from the oVirt upgrade.  Thoughts?

**Comment by suomiy** [comment]
> Is $VM_ID simply the VM name? If not, how can I find it?

It should be an id. You can find it in the vm edit dialog in the webadmin or here
```
curl -k -X GET \
  https://$ENGINE_ADDRESS/ovirt-engine/api/vms/ \
  -H "accept: application/xml" \
  -H "authorization: Basic $BASE_64_AUTH" 
```

also you can find the CONSOLE_ID in this request `... /api/vms/$VM_ID/graphicsconsoles`

>  Also noteworthy is that maybe perhaps these consoles aren't working from the webadmin page. 

> Although I seem to have the same desktop console problem for all VMs right now, even if moVirt does work.

That is weird. It may not be a moVirt issue. But anyway, I am curious, what these requests will return.

> I was able to download the vv file and Remote Viewer 

through webadmin?

>  Desktop was recently updated to Fedora 28 and I've been fighting other issues, but maybe this all stems from the oVirt upgrade. Thoughts?

not sure, but you can also check `/var/log/ovirt-engine/engine.log`


btw just in case, are you running the latest version of moVirt?

**Comment by jflorian** [comment]
Ah, I didn't think to edit the VM to get the ID.  I simply looked at the overview page.  Yes, I had meant I'd gotten the vv through the webadmin -- I didn't even try with curl because I was pretty sure the VM ID was different than a name since I see UUIDs all over in oVirt.  I have moVirt v2.0.2 (via auto-update) and that looks to be the latest according to the releases page here.

Okay, so now that I've got the VM ID thing down I can get you some request results.  This host doesn't offer a console option in moVirt:
```
 jflorian@zuul ~  curl -k -X GET   https://$ENGINE_ADDRESS/ovirt-engine/api/vms/$VM_ID/graphicsconsoles   -H "accept: application/xml"   -H "authorization: Basic $BASE_64_AUTH"
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<graphics_consoles>
    <graphics_console href="/ovirt-engine/api/vms/909ca5f3-84f1-46a6-8e79-2bc908477912/graphicsconsoles/7370696365" id="7370696365">
        <actions>
            <link href="/ovirt-engine/api/vms/909ca5f3-84f1-46a6-8e79-2bc908477912/graphicsconsoles/7370696365/proxyticket" rel="proxyticket"/>
            <link href="/ovirt-engine/api/vms/909ca5f3-84f1-46a6-8e79-2bc908477912/graphicsconsoles/7370696365/remoteviewerconnectionfile" rel="remoteviewerconnectionfile"/>
            <link href="/ovirt-engine/api/vms/909ca5f3-84f1-46a6-8e79-2bc908477912/graphicsconsoles/7370696365/ticket" rel="ticket"/>
        </actions>
        <protocol>spice</protocol>
        <vm href="/ovirt-engine/api/vms/909ca5f3-84f1-46a6-8e79-2bc908477912" id="909ca5f3-84f1-46a6-8e79-2bc908477912"/>
    </graphics_console>
</graphics_consoles>
```
Er, um I feel dense, but I don't understand how to get the CONSOLE_ID to get you the results of the vv download.

I thought I had some news about "fixing" VMs by editing them temporarily to be headless before setting them back to their normal console config.  That seemed to "repair" them for both moVirt and webadmin.  Then I was convinced it was merely because they'd been powered off (as is necessary for that change).  However, in playing with this one VM, I've seen it go back and forth.  Sometimes the webadmin only states that it's connected, other times I get the actually console.  Likewise, sometimes moVirt has the menu option, sometimes it doesn't.  At no time did I see anything unusual in the engine.log.

**Comment by jflorian** [comment]
Alrighty!  I think I can finally give you the details you've been asking for.  This VM is up, but not giving the console option in moVirt (as checked both before and after the results below):
~~~
 jflorian@zuul ~  curl -k -X GET \
    https://$ENGINE_ADDRESS/ovirt-engine/api/vms/$VM_ID/graphicsconsoles \
    -H "accept: application/xml" \
    -H "authorization: Basic $BASE_64_AUTH" 
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<graphics_consoles>
    <graphics_console href="/ovirt-engine/api/vms/b65a9c17-a071-4754-bad4-ff88f44006e0/graphicsconsoles/7370696365" id="7370696365">
        <actions>
            <link href="/ovirt-engine/api/vms/b65a9c17-a071-4754-bad4-ff88f44006e0/graphicsconsoles/7370696365/proxyticket" rel="proxyticket"/>
            <link href="/ovirt-engine/api/vms/b65a9c17-a071-4754-bad4-ff88f44006e0/graphicsconsoles/7370696365/remoteviewerconnectionfile" rel="remoteviewerconnectionfile"/>
            <link href="/ovirt-engine/api/vms/b65a9c17-a071-4754-bad4-ff88f44006e0/graphicsconsoles/7370696365/ticket" rel="ticket"/>
        </actions>
        <protocol>spice</protocol>
        <vm href="/ovirt-engine/api/vms/b65a9c17-a071-4754-bad4-ff88f44006e0" id="b65a9c17-a071-4754-bad4-ff88f44006e0"/>
    </graphics_console>
</graphics_consoles>

 jflorian@zuul ~  CONSOLE_ID=7370696365

 jflorian@zuul ~  curl -k -X GET \
    https://$ENGINE_ADDRESS/ovirt-engine/api/vms/$VM_ID/graphicsconsoles/$CONSOLE_ID \
    -H "accept: application/x-virt-viewer" \
    -H "authorization: Basic $BASE_64_AUTH"
[virt-viewer]
type=spice
host=172.16.7.8
port=5914
password=PAmUkUJeR/CE
# Password is valid for 120 seconds.
delete-this-file=1
fullscreen=0
toggle-fullscreen=shift+f11
release-cursor=shift+f12
secure-attention=ctrl+alt+end
tls-port=5915
enable-smartcard=0
enable-usb-autoshare=0
usb-filter=null
tls-ciphers=DEFAULT
host-subject=O=doubledog.org,CN=192.168.100.102
ca=-----BEGIN CERTIFICATE-----\nMIIDyTCCArGgAwIBAgICEAAwDQYJKoZIhvcNAQEFBQAwSjELMAkGA1UEBhMCVVMxFjAUBgNVBAoT\nDWRvdWJsZWRvZy5vcmcxIzAhBgNVBAMTGmV1cm9wYS5kb3VibGVkb2cub3JnLjY2MjI2MB4XDTE1\nMTIyMzIwMDEyMVoXDTI1MTIyMTIwMDEyMVowSjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDWRvdWJs\nZWRvZy5vcmcxIzAhBgNVBAMTGmV1cm9wYS5kb3VibGVkb2cub3JnLjY2MjI2MIIBIjANBgkqhkiG\n9w0BAQEFAAOCAQ8AMIIBCgKCAQEAys+T6HH5QyckpsSKOVjIz3a6vexymoKCaAw6/FHuKMLXHo9o\n2Y0qXl9/M62QVfObNW3H96lFZS1+H+MvNd2o/0qaYg4zEQ51CZZuy4BbCZ7paYEuqKbz8K5CO6qe\nEWXVf3mMQTyt8Ei/BTBB31pd6GYZSjgLpSJ1+JYQEsK1Bsz/xMnaq4snHqdOTET+cm0/dCQfd/0d\nf2WGhHse3I8hzWpJNroF0c+y4MG5oiNeQOi5KuJk6KqHoklThkMESJDjqso3oQlvBS8ZJu7b3MkT\nJJiN2C/XWPQ1IdpDQhB9jlcMTkETt2uDQSq3e7/ThJ+zpgpfn73UdHtQsNupDaCpCwIDAQABo4G4\nMIG1MB0GA1UdDgQWBBT7L4UEgiuXW+haOLGQXXd+kfXHfTBzBgNVHSMEbDBqgBT7L4UEgiuXW+ha\nOLGQXXd+kfXHfaFOpEwwSjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDWRvdWJsZWRvZy5vcmcxIzAh\nBgNVBAMTGmV1cm9wYS5kb3VibGVkb2cub3JnLjY2MjI2ggIQADAPBgNVHRMBAf8EBTADAQH/MA4G\nA1UdDwEB/wQEAwIBBjANBgkqhkiG9w0BAQUFAAOCAQEAqZDnj2XsKlOq4gnBhvvivQEGF+uoQE4f\nL4BWIzMdbZgn3o/CQixwMpq8OeY200I4k0BH6l/PEEXnWF6sM5zFcED5SWWnV31FF4mqfg3wEolg\nCgz80tniZUk1LsDkOxbRjQZjDostlhJet6C8Ib05obZXYpJIzpnBiD+c+xJ6vEgJKmUvOaXvE4xy\nCtU9QzHTdfGEP9+jJkzplk6XuM7CjSqWZhlrapeWfYY6RJ7rACeuU/RHZMBKFq1GAK+dYN46fJ6Y\nUya/SQHtLCt5sXVZbOsbrWyjqsIKzqYqRczTJ/khcN+pDrSfNmLrP6QTyONISipoWIBaAZiij7cY\n0Y8Uyg==\n-----END CERTIFICATE-----\n
secure-channels=main;inputs;cursor;playback;record;display;smartcard;usbredir
versions=rhev-win64:2.0-160;rhev-win32:2.0-160;rhel7:2.0-6;rhel6:99.0-1
newer-version-url=http://www.ovirt.org/documentation/admin-guide/virt/console-client-resources

[ovirt]
host=ovirt.doubledog.org:443
vm-guid=b65a9c17-a071-4754-bad4-ff88f44006e0
sso-token=4dWbbkOpR8YDLKVNlSt6QYRsfeptyeZ9ECt3px6e2okpZqcUsGhvDAttqHVbBr6RZHKJ2Ks3ky_Zx8OLn9pgug
admin=1
ca=-----BEGIN CERTIFICATE-----\nMIIDyTCCArGgAwIBAgICEAAwDQYJKoZIhvcNAQEFBQAwSjELMAkGA1UEBhMCVVMxFjAUBgNVBAoT\nDWRvdWJsZWRvZy5vcmcxIzAhBgNVBAMTGmV1cm9wYS5kb3VibGVkb2cub3JnLjY2MjI2MB4XDTE1\nMTIyMzIwMDEyMVoXDTI1MTIyMTIwMDEyMVowSjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDWRvdWJs\nZWRvZy5vcmcxIzAhBgNVBAMTGmV1cm9wYS5kb3VibGVkb2cub3JnLjY2MjI2MIIBIjANBgkqhkiG\n9w0BAQEFAAOCAQ8AMIIBCgKCAQEAys+T6HH5QyckpsSKOVjIz3a6vexymoKCaAw6/FHuKMLXHo9o\n2Y0qXl9/M62QVfObNW3H96lFZS1+H+MvNd2o/0qaYg4zEQ51CZZuy4BbCZ7paYEuqKbz8K5CO6qe\nEWXVf3mMQTyt8Ei/BTBB31pd6GYZSjgLpSJ1+JYQEsK1Bsz/xMnaq4snHqdOTET+cm0/dCQfd/0d\nf2WGhHse3I8hzWpJNroF0c+y4MG5oiNeQOi5KuJk6KqHoklThkMESJDjqso3oQlvBS8ZJu7b3MkT\nJJiN2C/XWPQ1IdpDQhB9jlcMTkETt2uDQSq3e7/ThJ+zpgpfn73UdHtQsNupDaCpCwIDAQABo4G4\nMIG1MB0GA1UdDgQWBBT7L4UEgiuXW+haOLGQXXd+kfXHfTBzBgNVHSMEbDBqgBT7L4UEgiuXW+ha\nOLGQXXd+kfXHfaFOpEwwSjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDWRvdWJsZWRvZy5vcmcxIzAh\nBgNVBAMTGmV1cm9wYS5kb3VibGVkb2cub3JnLjY2MjI2ggIQADAPBgNVHRMBAf8EBTADAQH/MA4G\nA1UdDwEB/wQEAwIBBjANBgkqhkiG9w0BAQUFAAOCAQEAqZDnj2XsKlOq4gnBhvvivQEGF+uoQE4f\nL4BWIzMdbZgn3o/CQixwMpq8OeY200I4k0BH6l/PEEXnWF6sM5zFcED5SWWnV31FF4mqfg3wEolg\nCgz80tniZUk1LsDkOxbRjQZjDostlhJet6C8Ib05obZXYpJIzpnBiD+c+xJ6vEgJKmUvOaXvE4xy\nCtU9QzHTdfGEP9+jJkzplk6XuM7CjSqWZhlrapeWfYY6RJ7rACeuU/RHZMBKFq1GAK+dYN46fJ6Y\nUya/SQHtLCt5sXVZbOsbrWyjqsIKzqYqRczTJ/khcN+pDrSfNmLrP6QTyONISipoWIBaAZiij7cY\n0Y8Uyg==\n-----END CERTIFICATE-----\n

 jflorian@zuul ~  curl -k -X GET   https://$ENGINE_ADDRESS/ovirt-engine/api/vms/$VM_ID/graphicsconsoles/$CONSOLE_ID   -H "accept: application/x-virt-viewer"   -H "authorization: Basic $BASE_64_AUTH" > /tmp/x.vv
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3590  100  3590    0     0  13914      0 --:--:-- --:--:-- --:--:-- 13861

 jflorian@zuul ~  remote-viewer /tmp/x.vv

(remote-viewer:31234): GSpice-WARNING **: 10:47:20.256: Error parsing auto-connect-filter string, keeping old filter
~~~

When the remote-viewer window opened, I was met again with the "Connected to graphic server" message just like what happens sometimes when I use the webadmin console and it decides to misbehave.

**Comment by suomiy** [comment]
Thanks a lot. It seems that everything is ok API-wise, so I guess there might be a bug in moVirt. I will look into it when I get some time.

The "Connected to graphic server" message, should be unrelated to moVirt. Anyway, please let me updated if you figure out something more.

**Comment by jflorian** [comment]
Thanks for looking into this and also showing me around the API a bit.  I will definitely keep you posted if I learn anything new.

**Comment by suomiy** [comment]
I am sorry, but I could not reproduce this. I tried it on engine v4.2.3 with multiple android versions and it worked.

Just keep it mind that the vm needs to be refreshed in moVirt (to download the consoles).

Btw, is SPICE capability visible in moVirt?
![spice](https://user-images.githubusercontent.com/3648838/40983943-011eaf3e-68e1-11e8-93ef-32bf24d60a19.png)

**Comment by jflorian** [comment]
> Just keep it mind that the vm needs to be refreshed in moVirt (to download the consoles).

Do you mean to say that I need to do something like swipe down while looking at the VM details screen, which gives me the spinner briefly?   If so, I am doing that.

I do see the SPICE capability, whether before or after doing the refresh I describe above, for both VMs that provide the console option and those that don't.  Here's a scrape, for example, showing that:

![screenshot_20180619-104200](https://user-images.githubusercontent.com/101996/41604774-03bfd006-73ae-11e8-8f75-2c2657de440a.png)

FWIW, in the web UI, all of my VMs show "SPICE" in the Graphics column of the VMs view.

Also interesting, [others too have noticed the desktop console problem](https://lists.ovirt.org/archives/list/users@ovirt.org/thread/ZQS676FGIRSLSXKSMIUEJAKY4RAVVA6F/) I noted above.

**Comment by suomiy** [comment]
> Do you mean to say that I need to do something like swipe down while looking at the VM details screen, which gives me the spinner briefly? If so, I am doing that.

yes

> I do see the SPICE capability, whether before or after doing the refresh I describe above, for both VMs that provide the console option and those that don't. Here's a scrape, for example, showing that:

I looked at the code again but could not find anything. There seems to be a bug there. I am sorry that I can't do anything about that until I can reproduce it.

What is your android version?

> FWIW, in the web UI, all of my VMs show "SPICE" in the Graphics column of the VMs view.
Also interesting, others too have noticed the desktop console problem I noted above.

I see, although it really seems the problem is in android menus misbehaving.
