### ISSUE TITLE
mOvirt api issue  with 4.3

### ISSUE THREAD

**Issue by hunter86bg** [oVirt/moVirt#305]
I have upgraded the engine to 4.3  (Hosts are having repo issues) and I receive the following:

Error details:
org.springframework.http.converter.HttpMessageNotReadableException: Could not read JSON: Unrecognized field "detail" (class org.ovirt.mobile.movirt.rest.dto.common.Statistic$Value), not marked as ignorable (one known property: "datum"])

**Comment by suomiy** [comment]
Thanks for reporting this.

In which part of application does these errors occur? 
Does the 4.3 work ok with correctly setup hosts?

**Comment by hunter86bg** [comment]
Sadly, I still cannot upgrade the hosts (package dependencies) - and I can't test that.
The errors occur when I try to refresh the hosts tab. On VM and storages tabs the app refreshes, but no data is provided.

**Comment by hunter86bg** [comment]
The strange thing is that after several refreshes -the Hosts and Storages tabs are being populated, while the VM tab gives the error.

**Comment by suomiy** [comment]
Should be fixed with https://github.com/oVirt/moVirt/pull/306. We will release a new version soon. Thanks again for reporting this.

**Comment by suomiy** [comment]
The new version was just released to Google Play (can take a day or so for full rollout). Hope everything will work well now, but feel free to reopen the issue if some new issue with 4.3 arises.
