### ISSUE TITLE
Feature Request: On powering down VM, try to shutdown first

### ISSUE THREAD

**Issue by hunter86bg** [oVirt/moVirt#309]
In movirt, we got a red arrow for bringing down a VM.
It will be nice  if movirt check if the VM has an agent installed and invoke graceful shutdown in such cases instead of pulling the plug.
I guess a timeout can be defined , which will trigger ungraceful 'power off'.

**Comment by suomiy** [comment]
I am sorry. but I don't much time for this now. I will have a chance to look at it in one month or so.

We could add a bit simpler solution - just adding a graceful shutdown action.
I like your idea much better though.

**Comment by hunter86bg** [comment]
You can ping me , once you add this feature and I can test it on a test VM.

**Comment by suomiy** [comment]
Sorry it took me so long to get back to this. I added the shutdown action. There is a PR for the new version: https://github.com/oVirt/moVirt/pull/311 - I will try to release it next week.


Let me know if it works for you ([apk link](https://github.com/oVirt/moVirt/blob/6db2a56e0a3546a0c6ab4081eea6bb0958082b7e/moVirt/moVirt-release.apk)), if you can spare some time to check it out.

**Comment by hunter86bg** [comment]
Great Job!
It shutdown both my Win10 and CentOS7 VMs without issues.
Also,my openBSD 6.6 (no guest agent is available)  is also powered off ungracefully  (that's expected - no guest tools) sl the feature is working.

**Comment by suomiy** [comment]
Good to hear that :) thanks for testing it

**Comment by suomiy** [comment]
released version 2.1 which should be available on Google Play soon
